# The URL the site will be built for
base_url = "https://organicmaps.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true
feed_filename = "rss.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = [".DS_Store"]

[markdown]
external_links_target_blank = true

# Allows to have localized URLs.
[slugify]
paths = "safe"

[extra]
stripe = "https://donate.organicmaps.app/"

# Default English translation
[translations]
address = "Address"
back = "Back to News"
contact = "Contact Us"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid="Install Organic Maps from F-Droid"
language = "English"
name = "Name"
token = "Token"

# Please sort all other translation sections and values in alphabetical order.
[languages.de]
[languages.de.translations]
address = "Adresse"
back = "Zurück zu Neuigkeiten"
contact = "Kontakt"
install-appgallery = "Organic Maps aus der Huawei AppGallery installieren"
install-appstore = "Installiere Organic Maps aus dem AppStore"
install-googleplay = "Organic Maps von Google Play installieren"
install-fdroid = "Organic Maps von F-Droid installieren"
language = "Deutsch"
name = "Name"
token = "Token"
[languages.fr]
[languages.fr.translations]
address = "Adresse"
back = "Retour aux actualités"
contact = "Contact"
install-appgallery = "Installez Organic Maps depuis l'AppGallery"
install-appstore = "Installez Organic Maps depuis l'AppStore"
install-googleplay = "Installez Organic Maps depuis Google Play"
install-fdroid = "Installez Organic Maps depuis F-Droid"
language = "Français"
name = "Nom"
token = "Jeton"
[languages.it]
[languages.it.translations]
address = "Indirizzo"
back = "Indietro"
contact = "Contattaci"
install-appgallery = "Installa Organic Maps da Huawei AppGallery"
install-appstore = "Installa Organic Maps dall'AppStore"
install-googleplay = "Installa Organic Maps da Google Play"
install-fdroid = "Installa Organic Maps da F-Droid"
language = "Italiano"
name = "Nome"
token = "Token"
[languages.pl]
[languages.pl.translations]
address = "Adres"
back = "Z powrotem"
contact = "Kontakt"
install-appgallery = "Zainstaluj Organic Maps z Huawei AppGallery"
install-appstore = "Zainstaluj Organic Maps z App Store"
install-googleplay = "Zainstaluj Organic Maps z Google Play"
install-fdroid = "Zainstaluj Organic Maps z F-Droid"
language = "Polski"
name = "Nazwa"
token = "Token"
[languages.ru]
[languages.ru.translations]
address = "Адрес"
back = "Назад"
contact = "Связаться с нами"
install-appgallery = "Установить Organic Maps из Huawei AppGallery"
install-appstore = "Установить Organic Maps из Apple AppStore"
install-googleplay = "Установить Organic Maps из Google Play"
install-fdroid = "Установить Organic Maps из F-Droid"
language = "Русский"
name = "Название"
token = "Токен"
[languages.tr]
[languages.tr.translations]
address = "Adres"
back = "Haberlere geri dön"
contact = "Bize ulaşın"
install-appgallery = "Organic Maps'i Huawei AppGallery'den İndir"
install-appstore = "Organic Maps'i AppStore'dan İndir"
install-googleplay = "Organic Maps'i Google Play'den İndir"
install-fdroid = "Organic Maps'i F-Droid'den İndir"
language = "Türkçe"
name = "İsim"
token = "Token"
[languages.id]
[languages.id.translations]
address = "Alamat"
back = "Kembali ke Berita"
contact = "Hubungi Kami"
install-appgallery = "Instal Organic Maps dari Huawei AppGallery"
install-appstore = "Instal Organic Maps dari AppStore"
install-googleplay = "Instal Organic Maps dari Google Play"
install-fdroid = "Instal Peta Organik dari F-Droid"
language = "Bahasa Indonesia"
name = "Nama"
token = "Token"
[languages.cs]
[languages.cs.translations]
address = "Adresa"
back = "Zpátky na Novinky"
contact = "Kontakt"
install-appgallery = "Nainstalujte Organic Maps z Huawei AppGallery"
install-appstore = "Nainstalujte Organic Maps z App Store"
install-googleplay = "Nainstalujte Organic Maps z Google Play"
install-fdroid = "Nainstalujte Organic Maps z F-Droid"
language = "čeština"
name = "Název"
token = "Token"
[languages.pt-BR.translations]
address = "Endereço"
back = "Voltar às Notícias"
contact = "Contact Us"
install-appgallery = "Instale Organic Maps a partir da Huawei AppGallery"
install-appstore = "Instale Organic Maps a partir da AppStore"
install-googleplay = "Instale Organic Maps a partir da Google Play"
install-fdroid = "Instale Organic Maps a partir do F-Droid"
language = "Português (Brazil)"
name = "Nome"
token = "Token"
[languages.es.translations]
address = "Dirección"
back = "Volver a noticias"
contact = "Contact Us"
install-appgallery = "Instalar Organic Maps desde la ApGallery de Huawei"
install-appstore = "Instalar Organic Maps desde el AppStore"
install-googleplay = "Instalar Organic Maps desde Google Play"
install-fdroid = "Instalar Organic Maps desde F-Droid"
language = "Español"
name = "Nombre"
token = "Token"
[languages.nl.translations]
address = "Adres"
back = "Terug naar Nieuws"
contact = "Contact Us"
install-appgallery = "Installeer Organic Maps in de Huawei AppGallery"
install-appstore = "Installeer Organic Maps in de AppStore"
install-googleplay = "Installeer Organic Maps op Google Play"
install-fdroid = "Installeer Organic Maps op F-Droid"
language = "Dutch"
name = "Naam"
token = "Token"
[languages.eu.translations]
address = "Helbidea"
back = "Back to News"
contact = "Contact Us"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid = "Install Organic Maps from F-Droid"
language = "Euskara"
name = "Izena"
token = "token"
